package com.oneclique.larolexia;

public interface RequestVariables {

    int REQUEST_SELECTED_USERNAME = 1001;
    int REQUEST_PLAYER_STATISTIC = 1100;


    String PLAYER_STATISTICS = "PLAYER STATISTICS";
    String SELECTED_USERNAME = "username";

    String CHOSEN_LETTER = "CHOSEN LETTER";
    String CHOSEN_SYLLABLE = "CHOSEN SYLLABLE";
    String SUMMATIVE_TEST_TITIK = "HULING PAGSUSULIT (TITIK)";
    String SUMMATIVE_TEST = "SUMMATIVE TEST";
    String SUMMATIVE_TEST_PANTIG = "HULING PAGSUSULIT (PANTIG)";
}
